import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/theme-provider';
import { ModeToggle } from '@/components/theme-toggle';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body className={ cn(
          "min-h-screen bg-background font-sans antialiased flex flex-col gap-2 md:gap-4",
          inter.className
        ) }
        >
          <NavBar />
          { children }</body>
      </ThemeProvider>
    </html>
  );
}

const NavBar = () => {
  return (

    <nav className='flex items-center justify-between flex-wrap p-6'>
      <ModeToggle />
    </nav>
  )
}